global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    monitor: cornix
scrape_configs:
  - job_name: node-exporter
    scrape_interval: 30s
    dns_sd_configs:
      - names:
          - node-exporter
        type: A
        port: 9100
  - job_name: cadvisor
    scrape_interval: 30s
    dns_sd_configs:
      - names:
          - cadvisor
        type: A
        port: 8080
  - job_name: traefik
    scrape_interval: 30s
    dns_sd_configs:
      - names:
          - "traefik"
        type: "A"
        port: 8080
